### ISSUE TITLE
0.2 release

### ISSUE THREAD

**Issue by est31** [qnighy/yasna.rs#18]
Due to the update of num to 0.2, and because we are using it in our public API, there have been breaking changes on our API. Therefore, the next release will be `0.2` and not `0.1.4`.

This issue is a tracking issue for the 0.2 release. If everything inside this issue is done, the 0.2 release will be released.

Things to be done until the 0.2 release:

- [x] Reducing dependencies (#7, #11)
- [x] Update of num to 0.2 (#12, #17)
- [x] Update of bit-vec to 0.5 (#20)
- [x] Adding all the features that [rcgen](https://github.com/est31/rcgen) needs (#15, #22)
- [x] Review of the remaining PRs in the queue (#9, #10)
- [x] Merging of #22 (#23)
